kind: Service
apiVersion: v1
metadata:
  #Service name
  name: docker-app-svc
spec:
  selector:
    app: my-docker-203607
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer